
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/dafi-dapp
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
